# Generated by Django 4.1.7 on 2023-04-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Course', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='studentprofile')),
            ],
        ),
    ]
